---
name: CI
on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Go build
        run: |
          os=(darwin linux)
          arch=(amd64)
          for goos in "${os[@]}"
          do
            for goarch in "${arch[@]}"
            do
              go clean -i
              echo "Building GOOS=$goos GOARCH=$goarch"
              GOOS=$goos GOARCH=$goarch go build
            done
          done
      - name: Check source is Go fmted
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Check source is Go fmt simplified
        run: diff -u <(echo -n) <(gofmt -s -d ./)
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: 2022.1.3
          install-go: false
      - name: Run unit tests
        run: go test -v ./...
      - name: Run integration tests
        run: go test -v -tags integration ./...
