---
name: CI
on:
  workflow_call:
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Go build
        run: go build
      - name: Check source is Go fmted
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Check source is Go fmt simplified
        run: diff -u <(echo -n) <(gofmt -s -d ./)
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go-version }}
      - name: Test
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
