---
name: CI
on:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-20.04
        experimental:
          - false
        include:
          - go-version: 1.18.x
            os: ubuntu-20.04
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Go build
        run: go build
      - name: Check source is Go fmted
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Check source is Go fmt simplified
        run: diff -u <(echo -n) <(gofmt -s -d ./)
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: master
          install-go: false
          cache-key: ${{ matrix.go-version }}
      - name: Test
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45.2
          skip-pkg-cache: true
          skip-build-cache: true
