---
name: CI
on:
  workflow_call:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Run YAML Lint
        uses: ibiqlik/action-yamllint@v3.1
        with:
          file_or_dir: .
          strict: true
          no_warnings: false
          config_data: |
            ---
            #
            # https://yamllint.readthedocs.io/en/stable/configuration.html
            #
            extends: default
            rules:
              braces:
                forbid: true
              brackets:
                max-spaces-inside: 1
                level: error
              colons:
                max-spaces-after: -1
                level: error
              commas:
                max-spaces-after: -1
                level: error
              empty-lines:
                max: 3
                level: error
              new-lines:
                type: unix
              new-line-at-end-of-file: disable
              hyphens:
                max-spaces-after: 1
              trailing-spaces:
                level: error
              line-length: disable
              comments:
                require-starting-space: false
                ignore-shebangs: false
                min-spaces-from-content: 1
              truthy: disable
  build:
    name: Build
    needs:
      - lint
    strategy:
      matrix:
        go-version:
          - 1.17.x
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Go build
        run: go build
      - name: Check source is Go fmted
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Check source is Go fmt simplified
        run: diff -u <(echo -n) <(gofmt -s -d ./)
      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: Test
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
